packages:
  - packages/shared
  - packages/renderer
  - packages/ui
  - packages/desktop
minimumReleaseAge: 10080 # delay 7days to mitigate supply-chain attack
minimumReleaseAgeExclude:
  - '@syuilo/aiscript'
  - '@pnpm/exe.darwin-arm64@12.3.4'
  - '@pnpm/exe.darwin-x64@12.3.4'
  - '@pnpm/exe.linux-arm64-musl@12.3.4'
  - '@pnpm/exe.linux-arm64@12.3.4'
  - '@pnpm/exe.linux-x64-musl@12.3.4'
  - '@pnpm/exe.linux-x64@12.3.4'
  - '@pnpm/exe.win32-arm64@12.3.4'
  - '@pnpm/exe.win32-x64@12.3.4'
  - pnpm@12.3.4
overrides:
  '@aiscript-dev/aiscript-languageserver': '-'
  '@tabler/icons-webfont>sharp': '-'
engineStrict: true
saveExact: true
shellEmulator: true
allowBuilds:
  electron-winstaller: false # Squirrel向けのビルド処理はNSISでは不要
  electron: true
  '@parcel/watcher': false
  esbuild: false
  pnpm: false
patchedDependencies:
  '@types/dom-webcodecs@0.1.13': patches/@types__dom-webcodecs@0.1.13.patch
